#!/bin/sh

targetBranch=$1
test -z "$targetBranch" && echo "ERROR: Please provide the target branch name to update" 1>&2 && exit 1

sourceBranch=${2:-'master-nsi'}

if [[ ! `git branch --list $targetBranch` ]]
then
    echo "'$targetBranch' branch does not exist in local repository"
    exit 1
fi

if currentBranch=$(git symbolic-ref --short -q HEAD)
then
    git stash
    git checkout "$targetBranch"
    git pull --no-edit origin "$sourceBranch"
    git push origin "$targetBranch"
    git checkout "$currentBranch"
    git stash pop

    echo "Updated the $targetBranch with changes from master-nsi"
    exit 0
else
    echo ERROR: Cannot find the current branch!
    exit 2
fi

