#!/bin/bash

remote=$1
test -z "$remote" && echo "ERROR: Please provide the git remote. eg. git reintegrate origin <branch name>" 1>&2 && exit 1

targetBranch=$2
test -z "$targetBranch" && echo "ERROR: Please provide the brnach name. eg. git reintegrate origin <branch name>" 1>&2 && exit 1

sourceBranch=${3:-'master-nsi'}
currentBranch=$(git symbolic-ref --short -q HEAD)

git ls-remote --exit-code "$remote" &> /dev/null
if test $? == 2; then
    echo ""
    echo "ERROR: git remote not found."
    exit 3;
fi

function main() {
      git checkout "$targetBranch"
      echo ""
      git pull --no-edit "$remote" "$sourceBranch"
      echo ""
      git push "$remote" "$targetBranch"
      echo ""
      git checkout "$currentBranch"
}

if [[ ! $(git branch --list $targetBranch) ]]
then
    echo ""
    echo "ERROR: branch \"$targetBranch\" does not exist in local repository"
    echo ""
    exit 1
fi

if [[ $currentBranch ]]; then
    echo ""

    if [[ $(git status --porcelain) ]]; then
      git stash
      echo ""
      main
      echo ""
      git stash pop
    else
      main
    fi

    echo ""
    echo "Updated the \"$targetBranch\" branch with changes from \"$sourceBranch\""
    exit 0
else
    echo ERROR: Cannot find the current branch!
    exit 2
fi

